[build]
  command = "pip install -r requirements.txt"
  functions = "backend"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9.7"

[functions]
  directory = "backend"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 