services:
  - type: web
    name: disease-prediction-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: PRODUCTION
        value: true
    healthCheckPath: /health 