services:
  - type: web
    name: disease-prediction-api
    env: python
    runtime: "python3.9"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PRODUCTION
        value: true
    healthCheckPath: /health 